### PR TITLE
Fix org on repo link

### PR DESCRIPTION
**Pull request by girasquid**
@jules2689 Tiny URL tweak for you :)

### CODE REVIEW

**Comment by girasquid** [comment]
The org is `bai` in the README - the link redirects you to the shopify/doggy repo, but it's a little weird to have the README for the repo referring to a URL that isn't where the repo lives anymore..

**Comment by jules2689** [comment]
i'm mostly confused why I was tagged, sorry

**Comment by kvs** [comment]
Woohoo, first non-Shopify contribution :-P

**Comment by jules2689** [comment]
LOL I forgot @girasquid wasnt shopify anymore. Super confused. Sorry >.<

**Pull request merged**
